# ===================================
#  List Behavior Config
# ===================================

title: backend::lang.user.role.list_title
list: $/liip/user/models/userrole/columns.yaml
modelClass: Liip\User\Models\UserRole
recordUrl: liip/user/userroles/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 25
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
